version: '3'
services:
  gotenberg:
    container_name: gotenberg-service
    # replace image with gotenberg/gotenberg:7-cloudrun or thecodingmachine/gotenberg:7-cloudrun
    # if you plan to run it on cloud
    image: gotenberg/gotenberg:7
    restart: always
    ports:
      - "3000:3000"
  api:
    container_name: document-template-processor-service
    build: .
    restart: always
    depends_on:
      - gotenberg
    ports:
      - "8000:8000"
    environment:
      - GOTENBERG_API_URL=http://gotenberg-service:3000
