apiVersion: v1
kind: Service
metadata:
  name: document-template-processing
  namespace: utils
spec:
  type: ClusterIP
  selector:
    app: document-template-processing
  ports:
  - name: http
    port: 8000
    targetPort: web
